const stuData = [
    {
        roll    :  01,
        name    : 'Rasel',
        fName   : 'Ataur',
        mName   : 'Rubi',
        bn      : 55,
        en      : 45,
        mth     : 45,
        rel     : 45,
        sc      : 45,
        ict     : 45,
        photo   : 'https://image.shutterstock.com/image-photo/confident-handsome-student-holding-books-260nw-366568778.jpg',
    }, 
    {
        roll    :  02,
        name    : 'Tasnim',
        fName   : 'Liyakot',
        mName   : 'amena',
        bn      : 75,
        en      : 85,
        mth     : 74,
        rel     : 98,
        sc      : 68,
        ict     : 75,
        photo   : 'https://img.freepik.com/free-photo/teenager-student-girl-yellow-pointing-finger-side_1368-40175.jpg?size=626&ext=jpg',
    },  
    {
        roll    :  03,
        name    : 'Rion',
        fName   : 'Rofiq',
        mName   : 'Rohima',
        bn      : 57,
        en      : 58,
        mth     : 47,
        rel     : 89,
        sc      : 75,
        ict     : 58,
        photo   : 'https://image.shutterstock.com/image-photo/portrait-smiling-young-college-student-260nw-1192615495.jpg',
    },
    {
        roll    :  04,
        name    : 'Bappi',
        fName   : 'Badhon',
        mName   : 'Rohima',
        bn      : 59,
        en      : 54,
        mth     : 42,
        rel     : 88,
        sc      : 77,
        ict     : 85,
        photo   : 'https://image.shutterstock.com/image-photo/hispanic-handsome-young-man-wearing-260nw-1908909961.jpg',
    },
    {
        roll    :  05,
        name    : 'Kamal',
        fName   : 'Milon',
        mName   : 'Rokeya',
        bn      : 85,
        en      : 48,
        mth     : 95,
        rel     : 25,
        sc      : 77,
        ict     : 85,
        photo   : 'https://thumbs.dreamstime.com/z/college-student-14606801.jpg',
    },
    {
        roll    :  06,
        name    : 'Shamim',
        fName   : 'Lichu',
        mName   : 'Kohinur',
        bn      : 85,
        en      : 98,
        mth     : 95,
        rel     : 98,
        sc      : 77,
        ict     : 85,
        photo   : 'https://thumbs.dreamstime.com/z/attractive-young-male-student-over-white-background-32276111.jpg',
    },
];
